const {
  PREFIX,
  DISCORD_TOKEN,
  DEFAULT_THUMBNAIL_URL,
  SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET,
  GENIUS_ACCESS_TOKEN,
  YOUTUBE_API_KEY,
} = require('dotenv').config().parsed;

module.exports = {
  PREFIX,
  DISCORD_TOKEN,
  DEFAULT_THUMBNAIL_URL,
  SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET,
  GENIUS_ACCESS_TOKEN,
  YOUTUBE_API_KEY,
};